@accentColor = #536DFE
Component.arc = 14
Button.arc = 12
TextComponent.arc = 12
ProgressBar.arc = 999
ScrollBar.thumbArc = 999
ScrollBar.trackArc = 999
Component.focusWidth = 1
Component.innerFocusWidth = 0
Button.margin = 7,12,7,12
TitlePane.unifiedBackground = true
