@accentColor = #536DFE
Component.arc = 14
Component.minimumWidth = 72
Button.arc = 12
Button.minimumHeight = 36
TextComponent.arc = 12
TextComponent.minimumHeight = 36
ProgressBar.arc = 999
ScrollBar.thumbArc = 999
ScrollBar.trackArc = 999
ScrollBar.showButtons = false
Component.focusWidth = 1
Component.innerFocusWidth = 0
Button.margin = 7,12,7,12
TitlePane.unifiedBackground = true
TitlePane.menuBarEmbedded = true
Component.arrowType = chevron
